openapi: 3.0.3
info:
  title: Pulse_Fit API
  version: 1.0.0
  description: |
    API documentation for Pulse_Fit backend. This spec covers the /api/users/me endpoints (profile management) and /api/users/me/progress. Expand for other endpoints as needed.
servers:
  - url: http://localhost:3000/api
paths:
  /users/me:
    get:
      summary: Get current user profile
      description: Returns the authenticated user's profile. Requires JWT authentication.
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success. Returns user profile data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "user-uuid"
                      full_name:
                        type: string
                        example: "Jane Doe"
                      age:
                        type: integer
                        example: 28
                      bio:
                        type: string
                        example: "Fitness enthusiast."
                      avatar_url:
                        type: string
                        example: "avatars/uuid.png"
                      avatar_signed_url:
                        type: string
                        example: "https://...signed-url..."
                      email:
                        type: string
                        example: "jane@example.com"
        '401':
          description: Unauthorized. JWT missing or invalid.
        '404':
          description: Profile not found.
        '500':
          description: Server error.
    put:
      summary: Update current user profile
      description: Update profile fields (full_name, age, bio, avatar). Avatar upload must be multipart/form-data. Requires JWT authentication.
      tags:
        - User
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                age:
                  type: integer
                bio:
                  type: string
                avatar:
                  type: string
                  format: binary
      responses:
        '200':
          description: Success. Returns updated user profile data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    $ref: '#/paths/~1users~1me/get/responses/200/content/application~1json/schema/properties/data'
        '400':
          description: Validation failed.
        '401':
          description: Unauthorized. JWT missing or invalid.
        '404':
          description: Profile not found.
        '500':
          description: Server error.
    delete:
      summary: Delete current user and profile
      description: Deletes the authenticated user's profile and account. Requires JWT authentication.
      tags:
        - User
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success. User and profile deleted.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '401':
          description: Unauthorized. JWT missing or invalid.
        '500':
          description: Server error.
  /users/me/progress:
    get:
      summary: Get user progress and insights
      description: >
        Returns aggregated progress data and insights for the authenticated user. Requires JWT authentication.
      tags:
        - Progress
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success. Returns progress data and insights.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      workouts_completed:
                        type: integer
                        example: 10
                      total_calories:
                        type: integer
                        example: 12000
                      activity_days:
                        type: integer
                        example: 14
                      goals_achieved:
                        type: integer
                        example: 2
                      last_activity_date:
                        type: string
                        format: date
                        example: "2025-06-24"
                      recent_activities:
                        type: array
                        items:
                          type: object
                          properties:
                            type:
                              type: string
                            duration:
                              type: number
                            calories:
                              type: number
                            date:
                              type: string
                              format: date
                      insights:
                        type: array
                        items:
                          type: string
        '401':
          description: Unauthorized. JWT missing or invalid.
        '500':
          description: Server error.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
