/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/../components/HapticTab`; params?: Router.UnknownInputParams; } | { pathname: `/../components/HelloWave`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ParallaxScrollView`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedText`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedView`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/IconSymbol`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/TabBarBackground.ios`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/TabBarBackground`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/IconSymbol.ios`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/../components/Collapsible`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ExternalLink`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/HapticTab`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/HelloWave`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ParallaxScrollView`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ThemedText`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ThemedView`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/IconSymbol`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/TabBarBackground.ios`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/TabBarBackground`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/IconSymbol.ios`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/../components/Collapsible${`?${string}` | `#${string}` | ''}` | `/../components/ExternalLink${`?${string}` | `#${string}` | ''}` | `/../components/HapticTab${`?${string}` | `#${string}` | ''}` | `/../components/HelloWave${`?${string}` | `#${string}` | ''}` | `/../components/ParallaxScrollView${`?${string}` | `#${string}` | ''}` | `/../components/ThemedText${`?${string}` | `#${string}` | ''}` | `/../components/ThemedView${`?${string}` | `#${string}` | ''}` | `/../components/ui/IconSymbol${`?${string}` | `#${string}` | ''}` | `/../components/ui/TabBarBackground.ios${`?${string}` | `#${string}` | ''}` | `/../components/ui/TabBarBackground${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `/../components/ui/IconSymbol.ios${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/../components/Collapsible`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ExternalLink`; params?: Router.UnknownInputParams; } | { pathname: `/../components/HapticTab`; params?: Router.UnknownInputParams; } | { pathname: `/../components/HelloWave`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ParallaxScrollView`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedText`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ThemedView`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/IconSymbol`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/TabBarBackground.ios`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/TabBarBackground`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/IconSymbol.ios`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
